config/routes.rb
TinymealRails::Application.routes.draw do
  get "welcome/index"

  resources :users
  
  scope ":handle", :as => "user" do
    resources :schedule
  end
  
  resources :foods, :meals

  root :to => 'welcome#index'
  
  match '/create_meals_for_the_week' => 'schedule#create_meals_for_the_week'
  match '/remove_food_from_meal' => 'foods#remove_food_from_meal'
  match "/foodnames" => 'foods#food_names'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :handle
  has_many :meals
  validates_presence_of :handle
  validates_uniqueness_of :handle
  # validate valid url option

  def to_param  # overridden
    handle
  end

  def create_meals_for_next_two_weeks
    [DateTime.now..DateTime.now + 14.days].each do |date|
      date.each do |day|
        begin
          day = Date.parse(day.strftime("%Y-%m-%d"))
          @meals = Meal.find(:all, :conditions => {:date => day.beginning_of_day..day.end_of_day, :user_id => id})
          if @meals.empty?
            Meal.create({:date => day, :name => "lunch", :user_id => id})
          end          
        rescue Exception => e
          raise e.inspect
        end
      end
    end
  end

end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  before_filter :set_user_and_build_schedule
  
  def index
    @meals = Meal.find(:all, :conditions => {:date => the_week_of, :name => "lunch", :user_id => @user.id}, :order => 'date')
    @next_weeks_meals = Meal.find(:all, :conditions => {:date => the_week_of(DateTime.now + 7.days), :name => "lunch", :user_id => @user.id})
    @this_week = the_week_of.first
    @food = Food.new

    @food_names = Food.all.map{ |f| f.name }
  end

  def the_week_of(start_date=DateTime.now)
    if params[:date]
      start_date = DateTime.parse(params[:date])
    end
    start_date.beginning_of_week.strftime("%Y-%m-%d")..start_date.end_of_week.strftime("%Y-%m-%d")
  end

  def set_user_and_build_schedule
    @user = User.find_by_handle(params[:handle]) || User.find(params[:handle])
    @user.create_meals_for_next_two_weeks
  end

end

app/helpers/schedule_helper.rb
module ScheduleHelper

  def default_accordion_group(meal)
    # Open today
    return true if DateTime.now.strftime("%Y-%m-%d") == meal.date.strftime("%Y-%m-%d")
    # Or open next day
    return true if (DateTime.now + 1.day).strftime("%Y-%m-%d") == meal.date.strftime("%Y-%m-%d")
  end

  def food_icon(food)
    url = ""
    icons = Dir.glob(Rails.root + "public/food-icons/*.gif")
    icons.each do |icon|
      icon_name = File.basename(icon).split(".")[0]
      # match icon_name to food.name
      r = Regexp.new(food.name.underscore.singularize)
      if icon_name.underscore =~ r || food.name.underscore =~ Regexp.new(icon_name.underscore)
        url = "/food-icons/#{icon_name}.gif"
      end
    end
    url
  end

end

app/views/schedule/_accordion.html.haml
.accordion-group.meal{:class => meal.date.strftime("%A").downcase}
  .accordion-heading
    %h3
      %a.accordion-toggle{:href => "#collapse#{meal.id}", 'data-toggle' => 'collapse', 'data-parent' => '#schedule'}
        = "#{meal.date.strftime("%A")}" 
        %span.count= "(#{meal.foods.length})"
  .accordion-body.collapse{:id => "collapse#{meal.id}", :class => opened ? 'in' : ''}
    .accordion-inner
      %table.table.table-hover{:id => "foodsInMeal#{meal.id}"}
        - meal.foods.each do |food|
          = render :partial => 'foods/food_list_item', :locals => {:food => food, :meal => meal}
                
      = form_for @food, :url => {:action => 'create', :controller => 'foods'}, :class => 'form-inline', :remote => true do |f|
        = f.text_field :name, :class => "input-medium", :placeholder => "food"
        = f.hidden_field :meal_ids, :value => meal.id.to_s
        = f.submit "Add", :class => "btn btn-primary"

app/views/schedule/_add_food_modal.html.haml
// Modal
.modal.hide.fade{:id => "meal#{meal.id}"}
  .modal-header
    %h3= meal.date.strftime("%A")
  .modal-body
    %h4 Foods in this meal
    %ul#foodsInMeal.connectedSortable
      %li Drag them here.
      - meal.foods.each do |food|
        %li= food.name
    %h4 All the foods
    %ul#foods.connectedSortable
      - meal.foods_not_in_meal.each do |food|
        %li= food.name
    .input-append
      = form_for @food, :url => {:action => 'create', :controller => 'foods'}, :remote => true do |f|
        = f.text_field :name, :class => "input-large"
        = f.collection_select(:meal_ids, Meal.all, :id, :date, :prompt => true, :selected => meal.id, :style => "display: none;")
        = f.submit "Add", :html => {:class => "btn", :type => "button"}

app/views/schedule/index.html.haml
#schedule.accordion.tab-content
  #thisWeek.tab-pane.active
    %h2= "This Week"
    - @meals.each do |meal|
      - opened = default_accordion_group(meal)
      = render 'accordion', :meal => meal, :opened => opened
  #nextWeek.tab-pane
    %h2= "Next Week"
    - @next_weeks_meals.each do |meal|
      - opened = default_accordion_group(meal)
      = render 'accordion', :meal => meal, :opened => opened