config/routes.rb
TinymealRails::Application.routes.draw do
  get "welcome/index"

  resources :users
  
  scope ":handle", :as => "user" do
    resources :schedule
  end
  
  resources :foods, :meals

  root :to => 'welcome#index'
  
  match '/create_meals_for_the_week' => 'schedule#create_meals_for_the_week'
  match '/remove_food_from_meal' => 'foods#remove_food_from_meal'
  match "/foodnames" => 'foods#food_names'

end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :name, :meal_ids
  has_and_belongs_to_many :meals
  validates_presence_of :name
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  respond_to :html, :js, :json
  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foods }
    end
  end

  def food_names
    @foods = Food.all
    respond_to do |format|
      format.json {render json: @foods.to_json(:only => [ :id, :name ])}
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/new
  # GET /foods/new.json
  def new
    @food = Food.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(params[:food])
    @meal = Meal.find(params[:food][:meal_ids]) if params[:food][:meal_ids]
    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /foods/1
  # PUT /foods/1.json
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }        
      else
        format.html { render action: "edit" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end


  def remove_food_from_meal
    @meal = Meal.find(params[:meal_id])
    @food = Food.find(params[:food_id])
    @meal.foods.delete(@food)
    respond_to do |format|
        format.html { redirect_to request.env['HTTP_REFERER'] }
        format.json {head :no_content}
        format.js
    end
  end

end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food_list_item.html.haml
%tr{:id => "food#{food.id}", :class => food.name}
  %td
    -if !food_icon(food).empty?
      = image_tag food_icon(food)
  %td= food.name
  %td
    %a{:href => remove_food_from_meal_path(:meal_id => meal.id, :food_id => food.id), 'data-remote' => 'true', :title => "remove"}
      %i.icon-remove

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/create.js.erb
var foodDiv = $("#foodsInMeal<%= @meal.id %>");
var container = $(foodDiv).parents()[2];
var span = $(container).find('span.count');
var tr = $("<%= escape_javascript(render :partial => 'foods/food_list_item', :locals => {:food => @food, :meal => @meal}) %>");

$(foodDiv).append($(tr).hide());
$(tr).fadeIn();
$(span).empty().append("(<%= @meal.foods.count %>)");
$(foodDiv).next("form").find("input#food_name").val("");

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h1>Listing foods</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @foods.each do |food| %>
  <tr>
    <td><%= food.name %></td>
    <td><%= link_to 'Show', food %></td>
    <td><%= link_to 'Edit', edit_food_path(food) %></td>
    <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/remove_food_from_meal.js.erb
var foodDiv = $("#foodsInMeal<%= @meal.id %>");
var container = $(foodDiv).parents()[2];
var span = $(container).find('span.count');

var tr = $("#foodsInMeal<%= @meal.id %> tr#food<%= params[:food_id] %>");

$(tr).addClass('error').fadeOut();
$(span).empty().append("(<%= @meal.foods.count %>)");

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @food.name %>
</p>

<ul>
  <% @food.meals.each do |meal| %>
    <li><%= meal %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>